name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 增加超时时间，MAME编译耗时较长

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential unzip python3 libsdl2-dev lua5.4
        # 创建交换空间防止内存不足
        sudo fallocate -l 4G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -m

    - name: Download MAME 0.279 source
      run: |
        wget https://github.com/mamedev/mame/archive/refs/tags/mame0279.zip
        unzip mame0279.zip
        mv mame-mame0279 mame-src

    - name: Prepare OSD layer
      run: |
        mkdir -p mame-src/src/osd
        cp -r android-MAME4droid/src/osd/myosd mame-src/src/osd/

    - name: Apply essential patches
      run: |
        cat > mame-src/patch.diff << 'EOF'
        diff --git a/scripts/genie.lua b/scripts/genie.lua
        --- a/scripts/genie.lua
        +++ b/scripts/genie.lua
        @@ -302,6 +302,9 @@
                defines {
                        "NO_USE_MIDI",
                        "USE_QTDEBUG=0",
        +               "SDLMAME_ANDROID=1",
        +               "__LIBRETRO__",
        +               "LUA_COMPAT_ALL"
                }
         
                -- disable exceptions
        EOF
        cd mame-src && patch -p1 < patch.diff

    - name: Set up Android NDK (r21e)
      uses: actions/setup-android@v2
      with:
        ndk-version: r21e  # 关键：使用兼容性最好的旧版NDK
        android-sdk-file: commandlinetools-linux-8512546_latest.zip

    - name: Build libMAME4droid.so
      run: |
        export NDK_ROOT=$ANDROID_NDK_ROOT
        cd mame-src
        make OSD=myosd TARGETOS=android NOWERROR=1 \
          CROSS_BUILD=1 TOOLS=0 REGENIE=1 \
          ARCHOPTS="-Wl,-soname,libMAME4droid.so -D__ANDROID__" \
          TARGET=mame SUBTARGET=arcade \
          ANDROID_ARCH=arm64 \
          -j2  # 减少并行数量防止OOM
        
        # 重命名并复制到Android项目
        mkdir -p ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a
        cp mamearcade64 ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a/libMAME4droid.so

    - name: Build Android APK
      run: |
        cd android-MAME4droid
        # 使用包含的gradlew确保版本兼容
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 7

    - name: Upload build logs (on failure)
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          mame-src/compile.log
          android-MAME4droid/app/build/**/logs/*.log
