name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '27.2.12479018'  # 精确匹配 gradle 配置

    - name: Build APK
      run: |
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MAME4droid-Debug
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 1
