name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 关键修复：验证目录结构
    - name: Verify repository structure
      run: |
        echo "当前工作目录: $(pwd)"
        ls -la
        
        # 1. 检查项目目录是否存在
        if [ ! -d "android-MAME4droid" ]; then
          echo "❌ 错误：android-MAME4droid 目录不存在"
          exit 1
        fi
        
        # 2. 检查 jni 目录是否存在
        if [ ! -d "android-MAME4droid/jni" ]; then
          echo "❌ 错误：jni 目录不存在，创建它..."
          mkdir -p android-MAME4droid/jni
          # 添加默认文件（如果需要）
          touch android-MAME4droid/jni/placeholder.txt
        fi
        
        # 3. 显示目录内容
        echo "android-MAME4droid 目录内容:"
        ls -la android-MAME4droid
        echo "jni 目录内容:"
        ls -la android-MAME4droid/jni
        
        echo "✅ 目录结构验证通过"

    # 下载 MAME 0.279 源码
    - name: Download MAME 0.279 source
      run: |
        wget -q https://github.com/mamedev/mame/archive/refs/tags/mame0279.zip -O mame-src.zip
        unzip -q mame-src.zip
        rm mame-src.zip
        mv mame-mame0279 mame-src
        echo "✅ MAME 0.279源码下载完成"

    # 复制项目文件（关键修复）
    - name: Copy project files to MAME source
      run: |
        # 1. 确保目标目录存在
        mkdir -p mame-src/jni
        
        # 2. 复制文件（如果源目录有内容）
        if [ "$(ls -A android-MAME4droid/jni)" ]; then
          cp -r android-MAME4droid/jni/* mame-src/jni/
        else
          echo "⚠️ 警告：jni 目录为空，跳过复制"
        fi
        
        # 3. 应用OSD修改
        echo "应用OSD修改..."
        if [ -f "mame-src/src/osd/android/makefile" ]; then
          sed -i 's/OLD_OSD_SETTING/NEW_OSD_SETTING/g' mame-src/src/osd/android/makefile
        else
          echo "⚠️ 警告：makefile 不存在，跳过修改"
        fi
        if [ -f "mame-src/src/osd/android/android.lua" ]; then
          sed -i 's/old_osd_function/new_osd_function/g' mame-src/src/osd/android/android.lua
        else
          echo "⚠️ 警告：android.lua 不存在，跳过修改"
        fi
        
        # 4. 验证复制结果
        echo "mame-src/jni 目录内容:"
        ls -la mame-src/jni
        echo "✅ 项目文件复制完成"

    # 后续步骤保持不变...
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      run: |
        # ...保持之前的Android SDK安装步骤...

    - name: Build MAME core library
      run: |
        # ...保持之前的MAME核心库构建步骤...

    - name: Build with Gradle
      run: |
        # ...保持之前的Gradle构建步骤...

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-0.279-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
