name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 关键修复：使用 Gradle 8.9
    - name: Build with Gradle
      run: |
        # 进入项目目录
        cd android-MAME4droid
        
        # 1. 下载 Gradle 8.9
        wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip -O gradle-bin.zip
        
        # 2. 解压 Gradle
        unzip -q gradle-bin.zip
        rm gradle-bin.zip
        
        # 3. 移除过时的 JVM 参数
        find . -name "gradle.properties" -exec sed -i '/MaxPermSize/d' {} \;
        
        # 4. 执行构建
        ./gradle-8.9/bin/gradle assembleDebug --no-daemon --stacktrace \
          -Dorg.gradle.jvmargs="-Xmx2048m" \
          -Dorg.gradle.daemon=false

    # 上传APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
