name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 关键修复：添加 Gradle Wrapper 修复步骤
    - name: Fix Gradle Wrapper
      run: |
        # 确保有 gradle/wrapper 目录
        mkdir -p gradle/wrapper
        
        # 下载正确的 gradle-wrapper.jar
        wget -q https://repo.maven.apache.org/maven2/org/grails/grails-gradle-wrapper/5.2.8/grails-gradle-wrapper-5.2.8.jar -O gradle/wrapper/gradle-wrapper.jar
        
        # 生成 gradlew 脚本
        echo '#!/bin/sh' > gradlew
        echo 'exec java -Dorg.gradle.appname=gradlew -classpath "gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"' >> gradlew
        chmod +x gradlew
        
        # 生成 gradle-wrapper.properties
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip" > gradle/wrapper/gradle-wrapper.properties

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      run: |
        # ...保持之前的Android SDK安装步骤不变...

    - name: Change to project directory
      run: |
        cd android-MAME4droid
        echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV

    # 验证 Gradle Wrapper 文件
    - name: Verify Gradle Wrapper
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        echo "验证Gradle Wrapper文件:"
        ls -la gradle/wrapper
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "❌ 错误: gradle-wrapper.jar 文件不存在!"
          exit 1
        fi
        if [ ! -f "gradlew" ]; then
          echo "❌ 错误: gradlew 文件不存在!"
          exit 1
        fi
        echo "✅ Gradle Wrapper 文件完整"

    - name: Build with Gradle
      working-directory: ${{ env.PROJECT_DIR }}
      run: |
        echo "当前工作目录: $(pwd)"
        echo "文件列表:"
        ls -la
        
        # 确保gradlew有执行权限
        chmod +x gradlew
        
        # 执行构建
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
