name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 修复点：使用正确的 Android SDK 设置方式
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      # 确保使用正确的 action 路径
      # 如果仍然失败，尝试以下替代方案：
      # uses: malinskiy/action-android/install-sdk@v1
      # 或
      # uses: wzieba/setup-android@v1

    # 手动安装 Android SDK 组件
    - name: Install Android SDK components
      run: |
        # 设置环境变量
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
        
        # 下载命令行工具
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        rm cmdline-tools.zip
        
        # 接受所有许可证
        yes | sdkmanager --licenses
        
        # 安装所需组件
        sdkmanager "platform-tools"
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platforms;android-34"
        sdkmanager "ndk;27.2.12479018"
        
        # 验证安装
        sdkmanager --list_installed

    - name: Verify repository content
      run: |
        echo "当前工作目录: $(pwd)"
        ls -la
        if [ ! -f "build.gradle" ]; then
          echo "错误: build.gradle 文件不存在!"
          exit 1
        fi
        if [ ! -d "app" ]; then
          echo "错误: app 目录不存在!"
          exit 1
        fi

    - name: Build with Gradle
      run: |
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/27.2.12479018"
        export PATH="$PATH:$ANDROID_NDK_HOME"
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 1
