name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 关键修复：完整的 Android SDK 安装
    - name: Setup Android SDK
      run: |
        # 1. 创建 Android SDK 目录
        ANDROID_SDK_ROOT="$HOME/android-sdk"
        mkdir -p "$ANDROID_SDK_ROOT"
        
        # 2. 下载命令行工具
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        
        # 3. 关键修复：创建目标目录
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        
        # 4. 解压到目标目录
        unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        rm cmdline-tools.zip
        
        # 5. 设置环境变量
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
        
        # 6. 关键修复：验证 sdkmanager 路径
        echo "验证 sdkmanager 路径:"
        which sdkmanager || {
          echo "❌ sdkmanager 未找到！"
          echo "目录内容:"
          ls -la "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
          exit 1
        }
        
        # 7. 手动接受许可证
        echo "手动接受 Android 许可证..."
        mkdir -p "$HOME/.android/licenses"
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$HOME/.android/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$HOME/.android/licenses/android-sdk-license"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$HOME/.android/licenses/android-sdk-license"
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> "$HOME/.android/licenses/android-sdk-license"
        
        # 8. 关键修复：指定 SDK 根目录
        sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools"
        sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "build-tools;34.0.0"
        sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platforms;android-34"
        sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "ndk;27.2.12479018"
        
        # 9. 持久化环境变量
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV

    # 下载 MAME 0.279 源码
    - name: Download MAME 0.279 source
      run: |
        wget -q https://github.com/mamedev/mame/archive/refs/tags/mame0279.zip -O mame-src.zip
        unzip -q mame-src.zip
        rm mame-src.zip
        mv mame-mame0279 mame-src
        echo "✅ MAME 0.279源码下载完成"

    # 构建 MAME 核心库
    - name: Build MAME core library
      run: |
        cd mame-src
        
        # 1. 生成项目文件
        make REGENIE=1 TARGETOS=android OSD=android
        
        # 2. 编译核心库
        make TARGETOS=android OSD=android ARCHITECTURE=arm64 \
          TARGET=arcade \
          SUBTARGET=mame \
          CROSS_BUILD=1 \
          NOWERROR=1 \
          TOOLS=1 \
          -j4
        
        # 3. 验证生成的库文件
        if [ ! -f "mamearcadearm64.so" ]; then
          echo "❌ 错误：MAME核心库未生成"
          exit 1
        fi
        
        # 4. 复制到Android项目
        mkdir -p ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a
        cp mamearcadearm64.so ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a/libMAME4droid.so
        echo "✅ MAME核心库生成成功（大小: $(du -h mamearcadearm64.so | cut -f1)）"

    # 构建APK
    - name: Build with Gradle
      run: |
        cd android-MAME4droid
        
        # 1. 使用Gradle 8.9
        wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip -O gradle-bin.zip
        unzip -q gradle-bin.zip
        rm gradle-bin.zip
        
        # 2. 执行构建
        ./gradle-8.9/bin/gradle assembleDebug --no-daemon --stacktrace
        
        # 3. 验证APK大小
        APK_SIZE=$(du -h app/build/outputs/apk/debug/*.apk | cut -f1)
        echo "APK大小: $APK_SIZE"
        if [[ ! $APK_SIZE =~ M ]]; then
          echo "❌ 错误：APK大小异常"
          exit 1
        fi

    # 上传APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-0.279-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
