name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 完全重写的 Android SDK 安装步骤（关键修复）
    - name: Setup Android SDK
      run: |
        # 1. 创建标准目录结构
        ANDROID_SDK_ROOT="$HOME/android-sdk"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        
        # 2. 下载命令行工具
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        rm cmdline-tools.zip
        
        # 3. 设置即时生效的环境变量
        export ANDROID_SDK_ROOT
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
        
        # 4. 验证安装
        which sdkmanager || { echo "❌ sdkmanager 未找到!"; exit 1; }
        echo "✅ sdkmanager 路径: $(which sdkmanager)"
        
        # 5. 接受许可证
        echo -e "y\ny\ny\ny\ny\ny\ny\ny\ny\ny" | sdkmanager --licenses
        
        # 6. 安装必要组件
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34" "ndk;27.2.12479018"
        
        # 7. 持久化环境变量
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV

    - name: Change to project directory
      run: cd android-MAME4droid

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
