name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: android-MAME4droid  # 关键修复：指定检出路径

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 修复点：手动设置 Android SDK
    - name: Setup Android SDK
      run: |
        # 设置 Android SDK 路径
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        mkdir -p $ANDROID_SDK_ROOT
        
        # 下载命令行工具
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        rm cmdline-tools.zip
        
        # 设置环境变量
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_PATH
        
        # 接受许可证
        yes | sdkmanager --licenses
        
        # 安装必要组件
        sdkmanager "platform-tools"
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platforms;android-34"
        sdkmanager "ndk;27.2.12479018"

    # 修复点：正确的工作目录
    - name: Verify repository content
      run: |
        echo "当前工作目录: $(pwd)"
        echo "文件列表:"
        ls -la
        
        # 检查关键文件（在 android-MAME4droid 目录下）
        if [ ! -f "build.gradle" ]; then
          echo "错误: build.gradle 文件不存在!"
          exit 1
        fi
        
        if [ ! -d "app" ]; then
          echo "错误: app 目录不存在!"
          exit 1
        fi
        
        if [ ! -f "app/build.gradle" ]; then
          echo "错误: app/build.gradle 文件不存在!"
          exit 1
        fi

    # 修复点：在正确目录执行构建
    - name: Build with Gradle
      run: |
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/27.2.12479018"
        export PATH="$PATH:$ANDROID_NDK_HOME"
        
        # 在 android-MAME4droid 目录执行构建
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
