name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 关键修复：使用真实编译生成库文件
    - name: Build MAME core library
      run: |
        # 1. 下载 MAME 0.279 源码
        wget -q https://github.com/mamedev/mame/archive/refs/tags/mame0279.zip -O mame-src.zip
        unzip -q mame-src.zip
        rm mame-src.zip
        mv mame-mame0279 mame-src
        
        # 2. 设置编译环境
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libsdl2-dev
        
        # 3. 编译核心库
        cd mame-src
        make TARGETOS=android TARGET=arcade SUBTARGET=mame OSD=android ARCHITECTURE=arm64 -j4
        
        # 4. 复制到项目
        mkdir -p ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a
        cp mamearcadearm64.so ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a/libMAME4droid.so
        
        # 5. 验证文件大小
        echo "核心库大小: $(du -h ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a/libMAME4droid.so | cut -f1)"
        if [ $(du -b ../android-MAME4droid/app/src/main/jniLibs/arm64-v8a/libMAME4droid.so | cut -f1) -lt 300000000 ]; then
          echo "❌ 错误：核心库大小不足 300MB"
          exit 1
        fi

    # 构建 Android APK
    - name: Build with Gradle
      run: |
        cd android-MAME4droid
        
        # 1. 使用 Gradle 8.9
        wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip -O gradle-bin.zip
        unzip -q gradle-bin.zip
        rm gradle-bin.zip
        
        # 2. 执行构建
        ./gradle-8.9/bin/gradle assembleDebug --no-daemon --stacktrace
        
        # 3. 验证 APK 大小
        APK_SIZE=$(du -h app/build/outputs/apk/debug/*.apk | cut -f1)
        echo "APK 大小: $APK_SIZE"
        if [[ ! $APK_SIZE =~ M ]]; then
          echo "❌ 错误：APK 大小异常"
          exit 1
        fi

    # 上传 APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAME4droid-0.279-APK
        path: android-MAME4droid/app/build/outputs/apk/debug/*.apk
        retention-days: 1
